name: Adsterra Bot

on:
  schedule:
    - cron: '*/15 * * * *'  # Setiap 15 menit
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: pip install requests beautifulsoup4  # Tambahan beautifulsoup4
      
    - name: Jalankan Adsterra Bot
      run: |
        echo "Mulai eksekusi pada $(date)" > bot.log
        python ./script_2.py >> bot.log 2>&1
        echo "Selesai eksekusi pada $(date)" >> bot.log
        
    - name: Tampilkan log di konsol
      run: cat bot.log
      
    - name: Simpan log
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: bot-logs-${{ github.run_id }}
        path: bot.log
        retention-days: 7
